### ISSUE TITLE
File Location Needs to be a variable, possibly passed in

### ISSUE THREAD

**Issue by abauer** [abauer/SDVRandomizer#7]
https://github.com/abauer/SDVRandomizer/blob/c9527d2c38931acf412a8c3d07c03a8158a1537a/DataObjects/CropData.py#L66

**Comment by nggonner** [comment]
Fixed, though I accidentally added it directly to the main branch so no pull request to reference :(

Added in commit c9527d2c38931acf412a8c3d07c03a8158a1537a
